### ISSUE TITLE
Umlauts (and other special characters) in URLs are not correctly encoded

### ISSUE THREAD

**Issue by stjosh** [nextcloud/ios-communication-library#10]
See https://github.com/nextcloud/ios/issues/959 for how this manifests in the latest Nextcloud iOS app.

From my understanding, the URL string would first have to be punycode-encoded before passing it to Alamofire - probably somewhere round here: 

https://github.com/nextcloud/ios-communication-library/blob/master/NCCommunication/NCCommunicationCommon.swift#L118

See also https://nshipster.com/characterset/#escaping-special-characters-in-urls 

Unfortunately, as I'm not a Swift developer, I can't provide a merge request for this.

**Comment by immortal79** [comment]
Same problem with '|' as described here: https://github.com/nextcloud/ios/issues/1214
Encoded character list is defined here:  https://github.com/nextcloud/ios-communication-library/blob/f7ee3a745282e8c015ab556621f20c23088add88/NCCommunication/NCCommunicationCommon.swift#L61 
Any reason why it is defined manually instead of .urlQueryAllowed set as suggested by @stjosh  ?

I will replace the set and do some tests to check if everything is still working as expected.

**Comment by Ivansss** [comment]
Fixed in #32
